### ISSUE TITLE
Feature Requests -- Various

### ISSUE THREAD

**Issue by themandalore** [tellor-io/lens#2]
- [x] Total payout at a given moment - so current reward per miner including tips and minting txn - added in https://github.com/tellor-io/lens/commit/96ca769a138cb77d0b4d49a372724cb249ea49ce
- [x] public getters of all of the hashed variables - added in https://github.com/tellor-io/lens/commit/22e4620f63887b5d2903ee0184ff6100d46645b8
- [x] add all usingTellor functions (if not already there) - added in https://github.com/tellor-io/lens/commit/d86e2f5af065a5e2db6f1d5bf61bbb7df18a0c99

**Comment by krasi-georgiev** [comment]
@themandalore, @JGcarv I think we are all good here. Can you please double-check and let me know what you think?
Here is the latest deployed version - https://rinkeby.etherscan.io/address/0x1ffA5c31e970D913064180163cf5a4373c25Affc#readContract

I even tested the `getLastNewValues` function  in the tellor API https://github.com/tellor-io/tellorREST/pull/23 and the speed is much better now.

**Comment by krasi-georgiev** [comment]
All implemented, please open another issue if you think anything is missing.
